"use client";
import {useMemo,useState} from "react";
import {CalendarDays,Clock3,Download,GraduationCap,Search,Sparkles} from "lucide-react";
import {Progress} from "@/components/ui/progress";
import {sessions,workshops} from "@/data/course";
const status={completed:"Finalizada",current:"En curso",upcoming:"Próxima"};
export default function Home(){const[q,setQ]=useState("");const list=useMemo(()=>sessions.filter(s=>(s.topic+s.activity+s.date).toLowerCase().includes(q.toLowerCase())),[q]);const done=sessions.filter(s=>s.status==="completed").length;return <main className="min-h-screen bg-[#f3f6f9] text-[#13253a]">
<header className="sticky top-0 z-20 border-b bg-white/90 backdrop-blur"><div className="mx-auto flex max-w-7xl items-center justify-between px-5 py-4"><a href="#" className="flex items-center gap-3"><span className="grid size-10 place-items-center rounded-xl bg-[#073763] text-white"><Sparkles size={18}/></span><b>IA · 2026</b></a><nav className="hidden gap-6 text-sm md:flex"><a href="#cronograma">Cronograma</a><a href="#talleres">Talleres</a><a href="#recursos">Recursos</a></nav></div></header>
<section className="bg-[#073763] text-white"><div className="mx-auto grid max-w-7xl gap-10 px-5 py-16 lg:grid-cols-[1.5fr_.8fr]"><div><span className="rounded-full border border-white/20 bg-white/10 px-3 py-1 text-xs">CC-IA001 · 4 créditos</span><h1 className="mt-6 text-4xl font-bold md:text-6xl">Introducción a la<br/><span className="text-[#65d6c4]">Inteligencia Artificial</span></h1><p className="mt-5 max-w-2xl text-lg text-blue-100">Aprendizaje práctico mediante talleres de búsqueda, optimización y aprendizaje computacional.</p><div className="mt-8 flex flex-wrap gap-6 text-sm text-blue-100"><span className="flex gap-2"><CalendarDays size={17}/>27 ago. — 9 oct.</span><span className="flex gap-2"><Clock3 size={17}/>20 sesiones</span><span className="flex gap-2"><GraduationCap size={17}/>Joaquín F. Sánchez</span></div></div><aside className="self-end rounded-3xl border border-white/20 bg-white/10 p-6"><div className="flex justify-between"><span>Avance</span><b className="text-3xl">{Math.round(done/20*100)}%</b></div><Progress value={done/20*100} className="mt-4 bg-white/20"/><p className="mt-5 text-sm text-blue-100">{done} sesiones realizadas · {20-done} pendientes</p></aside></div></section>
<div className="mx-auto max-w-7xl px-5 py-12"><section className="grid gap-4 md:grid-cols-3">{[["Primer corte","30%","Talleres 1, 2 y 3"],["Segundo corte","30%","Talleres 4 y 5"],["Tercer corte","40%","Talleres 6 y 7"]].map(c=><article key={c[0]} className="rounded-2xl border bg-white p-5 shadow-sm"><div className="flex justify-between"><b className="text-[#087f76]">{c[0]}</b><b>{c[1]}</b></div><p className="mt-3 text-sm text-slate-500">{c[2]}</p></article>)}</section>
<section id="cronograma" className="scroll-mt-20 pt-16"><Title a="Ruta de aprendizaje" b="Cronograma del curso"/><div className="mt-6 flex gap-3 rounded-xl border bg-white px-4 py-3"><Search size={18}/><input className="w-full outline-none" placeholder="Buscar tema o fecha…" value={q} onChange={e=>setQ(e.target.value)}/></div><div className="mt-4 space-y-3">{list.map(s=><article key={s.id} className="grid gap-3 rounded-2xl border bg-white p-5 shadow-sm md:grid-cols-[60px_145px_1fr_auto] md:items-center"><b className="grid size-11 place-items-center rounded-xl bg-[#e7f4f2] text-[#087f76]">{String(s.id).padStart(2,"0")}</b><div><b>{s.date}</b><p className="text-xs text-slate-500">{s.time}</p></div><div><h3 className="font-semibold">{s.topic}</h3><p className="text-sm text-slate-500">{s.activity}</p></div><div className="flex gap-2"><span className="rounded-full border bg-slate-50 px-3 py-1 text-xs">{status[s.status]}</span>{s.file&&<a href={s.file} download><Download/></a>}</div></article>)}</div></section>
<section id="talleres" className="scroll-mt-20 pt-16"><Title a="Evaluación" b="Talleres del curso"/><div className="mt-6 grid gap-4 md:grid-cols-2 lg:grid-cols-3">{workshops.map(w=><article key={w.id} className="rounded-2xl border bg-white p-5 shadow-sm"><div className="flex justify-between"><b className="grid size-10 place-items-center rounded-xl bg-[#073763] text-white">T{w.id}</b><b className="text-[#087f76]">{w.weight}%</b></div><h3 className="mt-5 font-semibold">{w.title}</h3><p className="mt-3 text-sm text-slate-500">Fecha: {w.date}</p><div className="mt-5 rounded-xl bg-slate-50 p-2 text-center text-sm text-slate-400">{w.file?"Descargar guía":"Guía próximamente"}</div></article>)}</div></section>
<section id="recursos" className="scroll-mt-20 pt-16"><Title a="Biblioteca" b="Recursos descargables"/><div className="mt-6 rounded-2xl border bg-white p-6 text-sm text-slate-600">Los materiales aparecerán aquí al agregar sus archivos en <code>public/materiales</code> y sus rutas en <code>data/course.ts</code>.</div></section></div>
<footer className="mt-12 bg-[#061f39] px-5 py-9 text-sm text-blue-100"><div className="mx-auto flex max-w-7xl justify-between"><span>Introducción a la IA · 2026</span><span>Joaquín F. Sánchez</span></div></footer></main>}
function Title({a,b}:{a:string;b:string}){return <div><p className="text-xs font-bold uppercase tracking-[.18em] text-[#087f76]">{a}</p><h2 className="mt-2 text-3xl font-bold">{b}</h2></div>}
